name: modelkeeper
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.6
  - numba=0.49.1
  - pip=20.0.2
  - pip:
    - torchvision  
    - transformers
    - matplotlib==3.1.3
    - tensorboardX==2.1
    - PyYAML
    - gdown
    - ray==1.8.0
    - networkx
    - onnx
    - paramiko
    - scp
    - pandas
    - ray[tune]
    - sentencepiece
    - datasets
    - ortools
    - torch
